/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zhkl0228_demumble_Demangler */

#ifndef _Included_com_github_zhkl0228_demumble_Demangler
#define _Included_com_github_zhkl0228_demumble_Demangler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zhkl0228_demumble_Demangler
 * Method:    demangle
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_zhkl0228_demumble_Demangler_demangle
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
